### PR TITLE
Proposed changes to incorporate more Endpoints

### PR DESCRIPTION
**Pull request by potatoqualitee**
Threw this together with Claude, the whole module and the OpenAI OpenAPI spec.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
hey @mkht -- are you interested in the expansion? If not, no problem. I can incorporate it in different ways.

**Comment by mkht** [comment]
I have no objection to accepting this change, but perhaps the current code is not sufficient. Many functions will break if this is not done.

Try running the test with `Invoke-Pester -Tag Offline`. I ran it and the test failed on 78 items.

**Comment by potatoqualitee** [comment]
awesome, it was more of a proposal. since you dont mind, ill fix 👍🏼

**Comment by potatoqualitee** [comment]
will return when im not burnedout

**Pull request closed without merging**
